//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancelSettings {
            get {
                return ResourceManager.GetString("btnCancelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string btnSaveSettings {
            get {
                return ResourceManager.GetString("btnSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Stats.
        /// </summary>
        public static string btnShowStats {
            get {
                return ResourceManager.GetString("btnShowStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championship selection:.
        /// </summary>
        public static string lblChamp {
            get {
                return ResourceManager.GetString("lblChamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the app?.
        /// </summary>
        public static string lblClosing {
            get {
                return ResourceManager.GetString("lblClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games drawn:.
        /// </summary>
        public static string lblDraws {
            get {
                return ResourceManager.GetString("lblDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string lblFullscreen {
            get {
                return ResourceManager.GetString("lblFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played:.
        /// </summary>
        public static string lblGamesPlayed {
            get {
                return ResourceManager.GetString("lblGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal differential:.
        /// </summary>
        public static string lblGoalDif {
            get {
                return ResourceManager.GetString("lblGoalDif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selection:.
        /// </summary>
        public static string lblLang {
            get {
                return ResourceManager.GetString("lblLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games lost:.
        /// </summary>
        public static string lblLosses {
            get {
                return ResourceManager.GetString("lblLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards in this match:.
        /// </summary>
        public static string lblPlayerCards {
            get {
                return ResourceManager.GetString("lblPlayerCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals scored in this match:.
        /// </summary>
        public static string lblPlayerScored {
            get {
                return ResourceManager.GetString("lblPlayerScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your wanted resolution:.
        /// </summary>
        public static string lblRes {
            get {
                return ResourceManager.GetString("lblRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals scored:.
        /// </summary>
        public static string lblScored {
            get {
                return ResourceManager.GetString("lblScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source selection:.
        /// </summary>
        public static string lblSource {
            get {
                return ResourceManager.GetString("lblSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals taken:.
        /// </summary>
        public static string lblTaken {
            get {
                return ResourceManager.GetString("lblTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games won:.
        /// </summary>
        public static string lblWins {
            get {
                return ResourceManager.GetString("lblWins", resourceCulture);
            }
        }
    }
}
